# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-31 23:50
from __future__ import unicode_literals

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operator',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='E-Mail'),
        ),
        migrations.AlterField(
            model_name='operator',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128),
        ),
    ]
