# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-01 00:05
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0002_auto_20180131_2350'),
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('town', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128)),
                ('phone2', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, verbose_name='Phone 2')),
                ('region', models.CharField(max_length=2)),
                ('lon', models.FloatField()),
                ('lat', models.FloatField()),
                ('pnt', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='terminal.Operator')),
            ],
            options={
                'verbose_name': 'Station',
                'verbose_name_plural': 'Stations',
            },
        ),
    ]
